# Generated by Django 3.2.18 on 2023-05-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230509_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='available_slots',
        ),
    ]
