# Generated by Django 3.2.18 on 2023-07-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='description',
            new_name='update_description',
        ),
    ]
