# Generated by Django 3.2.18 on 2023-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_description_updates_update_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='major_update',
            field=models.BooleanField(default=False),
        ),
    ]
